# Repo: Contoso/BuildTemplates
# File: common.yml
parameters:
  vmImage: 'ubuntu 16.04'

jobs:
- job: Build
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - bash: |
      cat > Dockerfile << EOF
      FROM microsoft/dotnet:2.2.100-sdk as build-env
      WORKDIR /build
      COPY . ./
      RUN dotnet restore ${{ parameters.serviceName }}.csproj
      RUN dotnet publish -c Release -o out ${{ parameters.serviceName }}.csproj
      FROM microsoft/dotnet:2.2.0-aspnetcore-runtime
      WORKDIR /app
      COPY --from=build-env /build/out ./
      EXPOSE 80
      ENTRYPOINT ["dotnet", "${{ parameters.serviceName}}.dll"]
      EOF
#  - script: cat Dockerfile
#  - script: docker build -f Dockerfile -t ${{ parameters.imageName }} .
  - task: Docker@1
    displayName: Build image
    inputs:
      command: build
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: docker-registry.grenzebach.edns.biz
      dockerFile: Dockerfile
      imageName: ${{ parameters.imageName }}
  - task: Docker@1
    displayName: Container registry login
    inputs:
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: docker-registry.grenzebach.edns.biz
      command: login
  - task: Docker@1
    displayName: Push image
    inputs:
      command: push
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: docker-registry.grenzebach.edns.biz
      imageName: $(imageName)
